# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63636071b67eb0858c0a9a7a51137d113e8860ce5ce6c4c6a464b4c33cbef45a2943d977724add74db1e0fd5268c7e1910f8069e69471f51f3e4abf3416efdd1

test:
  secret_key_base: 3b0385418acd3b53dafb3e8d498424d4f11805bea9d49f4c10cf92ca1708cb8f742a8f84d811d2e2a543df35d4eb9a53910cc61bf1c46d89bc853552dce83d8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
